-- 코드를 작성해주세요
SELECT 
    CASE 
        WHEN EXTRACT(MONTH FROM DIFFERENTIATION_DATE) <= 3 THEN '1Q'
        WHEN EXTRACT(MONTH FROM DIFFERENTIATION_DATE) <= 6 THEN '2Q'
        WHEN EXTRACT(MONTH FROM DIFFERENTIATION_DATE) <= 9 THEN '3Q'
        WHEN EXTRACT(MONTH FROM DIFFERENTIATION_DATE) <= 12 THEN '4Q'
    END AS QUARTER, 
    COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY 
    CASE 
        WHEN EXTRACT(MONTH FROM DIFFERENTIATION_DATE) <= 3 THEN '1Q'
        WHEN EXTRACT(MONTH FROM DIFFERENTIATION_DATE) <= 6 THEN '2Q'
        WHEN EXTRACT(MONTH FROM DIFFERENTIATION_DATE) <= 9 THEN '3Q'
        WHEN EXTRACT(MONTH FROM DIFFERENTIATION_DATE) <= 12 THEN '4Q'
    END
    
ORDER BY QUARTER ASC