-- 코드를 입력하세요
/*
몇 시에 입양이 가장 활발하게 일어나는지 
시간대 별 입양이 몇 건이 발생하는지
시간대 순으로 정렬
*/
SELECT EXTRACT(HOUR FROM DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE EXTRACT(HOUR FROM DATETIME) >= 9 AND EXTRACT(HOUR FROM DATETIME) < 20
GROUP BY EXTRACT(HOUR FROM DATETIME)
ORDER BY EXTRACT(HOUR FROM DATETIME)